language: ruby
rbenv:
- 2.5.3
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: XBrhm+KbiHCdU9PUpXZOGZlCdJvRdTMjhtOzpR5Tp/mQx2rdhYZmYmKtQtS/NV6s3wFTQhSqmmRMp+Okr+U6AfeeVoReF5fns+c041FTfBEg8pkA9Q92HTgt77ebEs/PkYyvooWstgi+udOHMQi+NKH2LgUjpaZkhTrZwbtQlPCZu/GVnwazfWqy0eBB7buTm7MICpIy9RYcxHaDz8dbumZ+IcXAOQcvsiPsCNynbirxdZMm7AJjynuv8Nb0qbKuJy0KpjzfthqD7n6XLvE2/OAvzAzFTKRAZFyPPiEHmZGfrxBoaj/Vb5mfgQSqRoeOOHD2IuZfNelIR6cN2nphjK14UrqwI978dSEeSQn624km3CfRHFz42vyEWf3vfrGRKrCn8zkJsay3eEQSQolFoU5Q+MlFCv6iW4qtmrjzw4ZMoRhNXnMzWjlCH5e4EuJxoTVvfjcMx1b3e58vVlUMVipnFxCFHO2I1bZAGZ6HGUEl/3QhiqzMIKeS6jawjoX3VdUR/ymJNqe0ojBfjbC4cjoLL10w1wT79G21WryCz2eAAggYe58jlqMQKmkuNj0DhvSp1g5W2z61IgT02MAE3ja9BO6GL02PG/KFwHkPhnpYep7yp/75U2kf+ciIxNfJTb292sJVHP1ws4QMm6xcvAepYFAlZoyjNOTo9RI0B6E=
  app: relocate-08-yelp-microservice
